const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('pcTools', {
  listApps: () => ipcRenderer.invoke('apps:list'),
  addApp: (item) => ipcRenderer.invoke('apps:add', item),
  removeApp: (id) => ipcRenderer.invoke('apps:remove', id),
  launch: (executable, protocol) => ipcRenderer.invoke('apps:launch', executable, protocol),
  scan: (target) => ipcRenderer.invoke('security:scan', target),
  vaultStatus: () => ipcRenderer.invoke('vault:status'),
  listAccounts: () => ipcRenderer.invoke('vault:list'),
  saveAccount: (account) => ipcRenderer.invoke('vault:save', account),
  deleteAccount: (id) => ipcRenderer.invoke('vault:delete', id),
  openSteam: () => ipcRenderer.invoke('vault:open-steam'),
  listProviders: () => ipcRenderer.invoke('providers:list'),
  openProviderLogin: (id) => ipcRenderer.invoke('providers:login', id),
  steamApiStatus: () => ipcRenderer.invoke('steamapi:status'),
  saveSteamApi: (config) => ipcRenderer.invoke('steamapi:save', config),
  loadSteamStats: () => ipcRenderer.invoke('steamapi:stats'),
  donationConfig: () => ipcRenderer.invoke('donation:config'),
  getProfile: () => ipcRenderer.invoke('profile:get'),
  saveProfile: (profile) => ipcRenderer.invoke('profile:save', profile),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  updateState: () => ipcRenderer.invoke('update:state'),
  loadLocale: (locale) => ipcRenderer.invoke('locale:load', locale),
  systemInfo: () => ipcRenderer.invoke('system:info'),
  openExternal: (url) => ipcRenderer.invoke('shell:open', url)
});
