let apps = []; let accounts = []; let activeFilter = 'Tümü'; let lang = localStorage.getItem('lang') || 'tr'; let translations = {};
const $ = (s) => document.querySelector(s); const icons = {Oyun:'◉', Uygulama:'▦', Geliştirme:'◇', İletişim:'◌', 'Tümü':'◈'};
function text(key){return translations[key] || key;} function toast(message, type='info'){const el=$('#toast');el.textContent=message;el.className=`toast visible ${type}`;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.className='toast',3200);} async function applyLanguage(){translations=await window.pcTools.loadLocale(lang);document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=text(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=text(el.dataset.i18nPlaceholder));render();}
async function load(){apps=await window.pcTools.listApps();accounts=await window.pcTools.listAccounts();renderAccounts();render();const info=await window.pcTools.systemInfo();$('#systemText').textContent=`${info.platform.toUpperCase()} · ${text('ready')}`;}
function renderAccounts(){const el=$('#accountsList');if(!accounts.length){el.classList.add('hidden');el.innerHTML='';return;}el.classList.remove('hidden');el.innerHTML=`<div class="accounts-head"><span class="eyebrow">${text('vaultTitle')}</span><button class="text-btn" id="openSteamBtn">${text('openSteam')} ↗</button></div><div class="account-grid">${accounts.map(a=>`<div class="account-card"><div class="account-avatar">${escapeHtml(a.label.slice(0,1).toUpperCase())}</div><div class="account-meta"><strong>${escapeHtml(a.label)}</strong><small>${escapeHtml(a.username)}</small></div><button class="account-delete" data-account-remove="${a.id}" title="${text('deleteAccount')}">×</button></div>`).join('')}</div>`;$('#openSteamBtn').addEventListener('click',()=>window.pcTools.openSteam());}
function render(){const q=$('#search').value.toLowerCase();const filtered=apps.filter(a=>(activeFilter==='Tümü'||a.category===activeFilter)&&a.name.toLowerCase().includes(q));$('#count').textContent=`${filtered.length} ${text('count')}`;$('#sectionTitle').textContent=activeFilter==='Tümü'?text('all'):activeFilter;$('#appGrid').innerHTML=filtered.map(card).join('');$('#empty').classList.toggle('hidden',filtered.length>0);$('#totalStat').textContent=apps.length;$('#gamesStat').textContent=apps.filter(a=>a.category==='Oyun').length;}
function card(a){const protocol=Boolean(a.protocol); const disabled=!a.available&&!protocol?'disabled':''; const title=protocol?text('launch'):(a.available?text('launch'):text('missing')); return `<article class="app-card"><div class="app-top"><div class="app-icon">${icons[a.category]||'⌁'}</div><div style="min-width:0"><div class="app-name" title="${escapeHtml(a.name)}">${escapeHtml(a.name)}</div><div class="app-source">${escapeHtml(a.source)} · ${escapeHtml(a.note||'')}</div></div></div><div class="app-bottom"><span class="tag">${escapeHtml(a.category)}</span><div><button class="launch" data-launch="${escapeHtml(a.executable)}" data-protocol="${protocol}" ${disabled}>${title}</button>${a.source==='Özel'?`<button class="close" data-remove="${a.id}" title="Remove" style="font-size:16px;margin-left:7px">×</button>`:''}</div></div></article>`;}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
document.addEventListener('click',async e=>{const nav=e.target.closest('.nav');if(nav){document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));nav.classList.add('active');activeFilter=nav.dataset.filter;render();}const launch=e.target.closest('[data-launch]');if(launch){try{const ok=await window.pcTools.launch(launch.dataset.launch,launch.dataset.protocol==='true');if(!ok)toast(text('launchFailed'),'error');else toast(`${launch.textContent} ✓`,'success');}catch{toast(text('launchFailed'),'error');}}const remove=e.target.closest('[data-remove]');if(remove){await window.pcTools.removeApp(remove.dataset.remove);toast(lang==='tr'?'Kütüphaneden kaldırıldı.':'Removed from library.','success');load();}});
document.addEventListener('click',async e=>{const accountRemove=e.target.closest('[data-account-remove]');if(accountRemove){await window.pcTools.deleteAccount(accountRemove.dataset.accountRemove);toast(lang==='tr'?'Hesap kasadan silindi.':'Account removed from vault.','success');load();}});
$('#search').addEventListener('input',render);$('#refreshBtn').addEventListener('click',()=>{load();toast(lang==='tr'?'Kütüphane yenilendi.':'Library refreshed.','success');});$('#rescanBtn').addEventListener('click',()=>{load();toast(lang==='tr'?'Sistem taranıyor…':'Scanning system…','info');});$('#githubBtn').addEventListener('click',()=>window.pcTools.openExternal('https://github.com/nkeremkarakas-hue/open-pc-tools'));$('#language').value=lang;$('#language').addEventListener('change',e=>{lang=e.target.value;localStorage.setItem('lang',lang);applyLanguage();});$('#addBtn').addEventListener('click',()=>$('#addDialog').showModal());$('#addForm').addEventListener('submit',async e=>{e.preventDefault();await window.pcTools.addApp({name:$('#nameInput').value,executable:$('#pathInput').value,category:$('#categoryInput').value});$('#addDialog').close();e.target.reset();toast(lang==='tr'?'Yazılım kütüphaneye eklendi.':'Software added to library.','success');load();});
$('#scanBtn').addEventListener('click',()=>{$('#scanResult').textContent='';$('#scanDialog').showModal();});$('#closeScan').addEventListener('click',()=>$('#scanDialog').close());$('#scanCancel').addEventListener('click',()=>$('#scanDialog').close());$('#runScan').addEventListener('click',async()=>{const target=$('#scanPath').value.trim();if(!target){$('#scanResult').textContent=text('enterPath');return;}$('#runScan').disabled=true;$('#scanResult').textContent=text('scanInProgress');const result=await window.pcTools.scan(target);$('#scanResult').textContent=result.message;$('#runScan').disabled=false;toast(result.message,result.ok?'success':'error');});
$('#accountBtn').addEventListener('click',async()=>{const status=await window.pcTools.vaultStatus();$('#accountResult').textContent=status.available?'':'OS güvenli kasası kullanılamıyor; parola kaydedilmedi.';$('#accountDialog').showModal();});$('#accountForm').addEventListener('submit',async e=>{e.preventDefault();const result=await window.pcTools.saveAccount({label:$('#accountLabel').value,username:$('#accountUsername').value,password:$('#accountPassword').value});if(!result.ok){$('#accountResult').textContent=result.message;return;}$('#accountDialog').close();e.target.reset();toast(lang==='tr'?'Hesap güvenli kasaya kaydedildi.':'Account saved securely.','success');load();});
$('#providerBtn').addEventListener('click',async()=>{const providers=await window.pcTools.listProviders();$('#providerGrid').innerHTML=providers.map(p=>`<div class="provider-card"><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.category)}</small></div><button class="launch provider-connect" data-provider="${p.id}">${text('connect')}</button></div>`).join('');$('#providerDialog').showModal();});$('#closeProviders').addEventListener('click',()=>$('#providerDialog').close());document.addEventListener('click',async e=>{const connect=e.target.closest('[data-provider]');if(connect){await window.pcTools.openProviderLogin(connect.dataset.provider);toast(lang==='tr'?'Resmî giriş sayfası açıldı.':'Official login page opened.','success');}});
async function boot(){await applyLanguage();await load();} boot();
